# Generated by Django 4.1.7 on 2023-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description_title', models.TextField()),
                ('more_about_item', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cosmetics')),
                ('category', models.CharField(choices=[('BC', 'Body Cream'), ('BW', 'Body Wash'), ('BS', 'Black Soap'), ('LS', 'Liquid Soap'), ('FBL', 'Face & Body Lotion'), ('FBM', 'Face & Body Moisturiser')], max_length=3)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
            ],
        ),
    ]
