# Generated by Django 4.1.7 on 2023-03-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0003_item_category_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snail'),
        ),
    ]
