# Generated by Django 4.1.7 on 2023-03-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0004_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='description_title',
        ),
        migrations.AddField(
            model_name='item',
            name='more_about_item',
            field=models.TextField(default='More about this item'),
            preserve_default=False,
        ),
    ]
