# Generated by Django 4.1.7 on 2023-03-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0005_rename_description_item_description_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
