# Generated by Django 4.1.7 on 2023-03-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
