# Generated by Django 4.1.7 on 2023-04-03 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snail', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('shipping_address_1', models.CharField(max_length=150)),
                ('nearest_bustop', models.CharField(max_length=150)),
                ('shipping_country', models.CharField(max_length=25)),
                ('shipping_state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=15)),
                ('save_info', models.BooleanField(default=False)),
                ('use_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
