# Generated by Django 4.1.7 on 2023-04-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0013_order_payment_alter_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='save_info',
        ),
    ]
