# Generated by Django 4.1.7 on 2023-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0014_remove_address_save_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
