# Generated by Django 4.1.7 on 2023-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0016_alter_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Successful'), ('P', 'Pending'), ('F', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
