# Generated by Django 4.1.7 on 2023-04-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0017_remove_payment_payment_charge_id_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
