# Generated by Django 4.1.7 on 2023-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0018_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
