# Generated by Django 4.1.7 on 2023-04-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0019_order_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
