# Generated by Django 4.1.7 on 2023-04-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0026_cosmetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snail',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Cosmetic Item List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('snail.item',),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Snail Item List'},
        ),
    ]
