# Generated by Django 4.1.7 on 2023-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snail', '0027_snail_alter_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('how_can_we_help', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='snail',
            options={'verbose_name_plural': 'Snail Item List'},
        ),
    ]
